import {
  Home,
  LogIn,
  UserPlus,
  KeyRound,
  Info,
  Mail,
  BookOpen,
  FileText,
  Shield,
  User,
  Bell,
  GraduationCap,
  CreditCard,
  LayoutDashboard,
  Users,
  School,
  FolderOpen,
  DollarSign,
  BarChart3,
  Plus,
  Edit,
  Map,
  Compass,
  CalendarCheck,
  Star,
  ClipboardList,
  Bike,
  Building2,
  Music,
  Coffee,
} from "lucide-react";

// Centralized route paths for students and teachers
const routes = {
  out: {
    home: {
      name: "Home",
      url: "/",
      icon: <Home className="h-4 w-4" />,
    },
    login: {
      name: "Log In",
      url: "/login",
      icon: <LogIn className="h-4 w-4" />,
    },
    signup: {
      name: "Sign Up",
      url: "/signup",
      icon: <UserPlus className="h-4 w-4" />,
    },
    forgotPassword: {
      name: "Forgot Password",
      url: "/forgot-password",
      icon: <KeyRound className="h-4 w-4" />,
    },
    about: {
      name: "About",
      url: "/about",
      icon: <Info className="h-4 w-4" />,
    },
    contact: {
      name: "Contact",
      url: "/contact",
      icon: <Mail className="h-4 w-4" />,
    },
    termsAndConditions: {
      name: "Terms and Conditions",
      url: "/terms-and-conditions",
      icon: <FileText className="h-4 w-4" />,
    },
    privacyPolicy: {
      name: "Privacy Policy",
      url: "/policy",
      icon: <Shield className="h-4 w-4" />,
    },
  },
  common: {
    profile: {
      name: "Profile",
      url: "/profile",
      icon: <User className="h-4 w-4" />,
      menu: true,
      order: 1,
      group: 10,
    },
    notifications: {
      name: "Notifications",
      url: "/notifications",
      icon: <Bell className="h-4 w-4" />,
      // menu: true,
      order: 2,
      group: 10,
    },
    info: {
      name: "Info",
      url: "/info",
      icon: <Info className="h-4 w-4" />,
      menu: true,
      order: 3,
      group: 10,
    },
  },
  traveller: {
    welcome: {
      name: "Welcome",
      url: "/welcome",
      icon: <Map className="h-4 w-4" />,
    },
    dashboard: {
      name: "Dashboard",
      url: "/traveller",
      icon: <LayoutDashboard className="h-4 w-4" />,
      menu: true,
      order: 1,
      group: 1,
    },
    payments: {
      name: "Payments",
      url: "/traveller/payments",
      icon: <CreditCard className="h-4 w-4" />,
    },
    applyForServiceProvider: {
      name: "Apply for Service Provider",
      url: "/traveller/apply-for-service-provider",
      icon: <Plus className="h-4 w-4" />,
    },
    hotels: {
      name: "Hotels",
      url: "/traveller/hotels",
      icon: <Building2 className="h-4 w-4" />,
      menu: true,
      order: 2,
      group: 1,
    },
    transport: {
      name: "Transport",
      url: "/traveller/transport",
      icon: <Bike className="h-4 w-4" />,
      menu: true,
      order: 3,
      group: 1,
      menu: true,
    },
    // club: {
    //   name: "Club Service",
    //   url: "/traveller/clubs",
    //   icon: <Music className="h-4 w-4" />,
    //   menu: true,
    //   order: 5,
    //   group: 1,
    // },
    restaurant: {
      name: "Restaurant Service",
      url: "/traveller/restaurants",
      icon: <Coffee className="h-4 w-4" />,
      menu: true,
      order: 6,
      group: 1,
    },
    experiences: {
      name: "Experiences",
      url: "/traveller/experiences",
      icon: <Compass className="h-4 w-4" />,
      menu: true,
      order: 3,
      group: 1,
    },
    experienceDetail: {
      name: "Experience Detail",
      url: "/traveller/experiences/:id",
      icon: <Bike className="h-4 w-4" />,
    },
    myBookings: {
      name: "My Bookings",
      url: "/traveller/my-bookings",
      icon: <CalendarCheck className="h-4 w-4" />,
      menu: true,
      order: 1,
      group: 2,
    },
    myReviews: {
      name: "My Reviews",
      url: "/traveller/my-reviews",
      icon: <Star className="h-4 w-4" />,
      menu: true,
      order: 2,
      group: 2,
    },
  },
  serviceProvider: {
    dashboard: {
      name: "Dashboard",
      url: "/service-provider",
      icon: <LayoutDashboard className="h-4 w-4" />,
      menu: true,
      order: 1,
      group: 1,
    },
    hotelManagement: {
      name: "Hotel Management",
      url: "/service-provider/hotel-management",
      icon: <Building2 className="h-4 w-4" />,
      menu: true,
      order: 1,
      group: 2,
    },
    createHotel: {
      name: "Create Hotel",
      url: "/service-provider/hotel-management/create",
      icon: <Plus className="h-4 w-4" />,
    },
    editHotel: {
      name: "Edit Hotel",
      url: "/service-provider/hotel-management/edit/:hotelId",
      icon: <Edit className="h-4 w-4" />,
    },
    restaurantManagement: {
      name: "Restaurant Management",
      url: "/service-provider/restaurant-management",
      icon: <Coffee className="h-4 w-4" />,
      menu: true,
      order: 2,
      group: 2,
    },
    createRestaurant: {
      name: "Create Restaurant",
      url: "/service-provider/restaurant-management/create",
      icon: <Plus className="h-4 w-4" />,
    },
    editRestaurant: {
      name: "Edit Restaurant",
      url: "/service-provider/restaurant-management/edit/:restaurantId",
      icon: <Edit className="h-4 w-4" />,
    },
    transportManagement: {
      name: "Transport Management",
      url: "/service-provider/transport-management",
      icon: <Bike className="h-4 w-4" />,
      menu: true,
      order: 2,
      group: 2,
    },
    myServices: {
      name: "My Services",
      url: "/service-provider/my-services",
      icon: <Map className="h-4 w-4" />,
    },
    analytics: {
      name: "Analytics",
      url: "/service-provider/analytics",
      icon: <BarChart3 className="h-4 w-4" />,
    },
    experienceManagement: {
      name: "Experience Management",
      url: "/service-provider/experiences",
      icon: <Compass className="h-4 w-4" />,
      menu: true,
      order: 3,
      group: 2,
    },
    createExperience: {
      name: "Create Experience",
      url: "/service-provider/experiences/create",
      icon: <Plus className="h-4 w-4" />,
    },
    editExperience: {
      name: "Edit Experience",
      url: "/service-provider/experiences/edit/:id",
      icon: <Edit className="h-4 w-4" />,
      menu: false,
    },
    bookingRequests: {
      name: "Booking Requests",
      url: "/service-provider/booking-requests",
      icon: <ClipboardList className="h-4 w-4" />,
      menu: true,
      order: 2,
      group: 1,
    },
    reviews: {
      name: "Reviews",
      url: "/service-provider/reviews",
      icon: <Star className="h-4 w-4" />,
      menu: true,
      order: 3,
      group: 1,
    },
  },
  admin: {
    dashboard: {
      name: "Dashboard",
      url: "/admin",
      icon: <LayoutDashboard className="h-4 w-4" />,
      // menu: true,
      order: 1,
      group: 1,
    },
    travellerManagement: {
      name: "Traveller Management",
      url: "/admin/traveller-management",
      icon: <Users className="h-4 w-4" />,
      menu: true,
      order: 2,
      group: 1,
    },
    serviceProviderManagement: {
      name: "Service Provider Management",
      url: "/admin/service-provider-management",
      icon: <Users className="h-4 w-4" />,
      menu: true,
      order: 3,
      group: 1,
    },
    hotelManagement: {
      name: "Hotel Management",
      url: "/admin/hotel-management",
      icon: <Building2 className="h-4 w-4" />,
      menu: true,
      order: 1,
      group: 2,
    },
    transportManagement: {
      name: "Transport Management",
      url: "/admin/transport-management",
      icon: <Bike className="h-4 w-4" />,
      menu: true,
      order: 2,
      group: 2,
    },
    // clubManagement: {
    //   name: "Club Service",
    //   url: "/admin/club-management",
    //   icon: <Music className="h-4 w-4" />,
    //   menu: true,
    //   order: 3,
    //   group: 2,
    // },
    restaurantManagement: {
      name: "Restaurant Service",
      url: "/admin/restaurant-management",
      icon: <Coffee className="h-4 w-4" />,
      menu: true,
      order: 4,
      group: 2,
    },
    experienceManagement: {
      name: "Experience Management",
      url: "/admin/experience-management",
      icon: <Compass className="h-4 w-4" />,
      menu: true,
      order: 3,
      group: 2,
    },
    analytics: {
      name: "Analytics",
      url: "/admin/analytics",
      icon: <BarChart3 className="h-4 w-4" />,
      order: 1,
      group: 4,
    },
  },
};

export { routes };
